"""
Permanent SQLite storage for the AI Betting Analytics module.

Tables (data/analytics.db, never deleted, never overwritten in place --
`results` rows are appended once per prediction and never updated again):

- predictions        one row per recommendation ever generated by the bot
- results            one row per settled prediction (WON/LOST/VOID/...)
- daily_statistics   materialized aggregate, rebuilt from predictions+results
- market_statistics   ""
- league_statistics   ""
- signal_statistics   ""
- monthly_statistics  ""

The five *_statistics tables are derived/materialized views: they are
safely recomputed from the append-only predictions/results tables by
`refresh_statistics()` (a full rebuild, not a mutation of raw history).
"""

from __future__ import annotations

import datetime
import os
import sqlite3
import threading
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from analytics.config import ANALYTICS_DB_PATH, DEFAULT_STAKE, LOSS_STATUSES, VOID_RESULT_STATUSES, WIN_STATUSES


def _utc_now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat()


class DuplicateAnalyticsPredictionError(Exception):
    """Raised when the exact same (fixture_id, market) prediction was
    already recorded -- protects against double-counting the same
    recommendation if a daily archive is ever (re-)computed twice."""


@dataclass
class PredictionRow:
    id: int
    created_at: str
    match_datetime: Optional[str]
    sport: Optional[str]
    country: Optional[str]
    league: Optional[str]
    fixture_id: Optional[int]
    home_team: Optional[str]
    away_team: Optional[str]
    market: str
    market_label: Optional[str]
    selection: Optional[str]
    odds: Optional[float]
    estimated_probability: Optional[float]
    signal_level: Optional[str]
    reason: Optional[str]
    model_version: Optional[str]
    archive_version: Optional[str]
    prediction_source: Optional[str]


class AnalyticsStorage:
    def __init__(self, db_path: str = ANALYTICS_DB_PATH, *, now: Optional[datetime.datetime] = None) -> None:
        self.db_path = db_path
        directory = os.path.dirname(db_path)
        if directory:
            os.makedirs(directory, exist_ok=True)
        self._lock = threading.Lock()
        self._conn = sqlite3.connect(db_path, check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._now = now
        self._create_schema()

    def _now_iso(self) -> str:
        return self._now.isoformat() if self._now is not None else _utc_now_iso()

    def close(self) -> None:
        self._conn.close()

    # -- schema ---------------------------------------------------------------

    def _create_schema(self) -> None:
        with self._lock, self._conn:
            self._conn.execute(
                """
                CREATE TABLE IF NOT EXISTS predictions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    created_at TEXT NOT NULL,
                    match_datetime TEXT,
                    sport TEXT,
                    country TEXT,
                    league TEXT,
                    fixture_id INTEGER,
                    home_team TEXT,
                    away_team TEXT,
                    market TEXT NOT NULL,
                    market_label TEXT,
                    selection TEXT,
                    odds REAL,
                    estimated_probability REAL,
                    signal_level TEXT,
                    reason TEXT,
                    model_version TEXT,
                    archive_version TEXT,
                    prediction_source TEXT,
                    dedup_key TEXT NOT NULL UNIQUE
                )
                """
            )
            self._conn.execute(
                """
                CREATE TABLE IF NOT EXISTS results (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    prediction_id INTEGER NOT NULL UNIQUE,
                    fixture_id INTEGER,
                    final_home_score INTEGER,
                    final_away_score INTEGER,
                    status TEXT NOT NULL,
                    won INTEGER NOT NULL DEFAULT 0,
                    lost INTEGER NOT NULL DEFAULT 0,
                    void INTEGER NOT NULL DEFAULT 0,
                    profit REAL NOT NULL DEFAULT 0,
                    stake REAL NOT NULL DEFAULT 0,
                    settlement_explanation TEXT,
                    checked_at TEXT NOT NULL,
                    FOREIGN KEY (prediction_id) REFERENCES predictions(id)
                )
                """
            )
            for table, bucket_col in (
                ("daily_statistics", "bucket_date"),
                ("monthly_statistics", "bucket_month"),
                ("market_statistics", "market"),
                ("league_statistics", "league"),
                ("signal_statistics", "signal_level"),
            ):
                self._conn.execute(
                    f"""
                    CREATE TABLE IF NOT EXISTS {table} (
                        {bucket_col} TEXT PRIMARY KEY,
                        total_predictions INTEGER NOT NULL DEFAULT 0,
                        settled_predictions INTEGER NOT NULL DEFAULT 0,
                        wins INTEGER NOT NULL DEFAULT 0,
                        losses INTEGER NOT NULL DEFAULT 0,
                        voids INTEGER NOT NULL DEFAULT 0,
                        half_wins INTEGER NOT NULL DEFAULT 0,
                        half_losses INTEGER NOT NULL DEFAULT 0,
                        win_rate REAL NOT NULL DEFAULT 0,
                        roi REAL NOT NULL DEFAULT 0,
                        profit REAL NOT NULL DEFAULT 0,
                        avg_odds REAL NOT NULL DEFAULT 0,
                        updated_at TEXT NOT NULL
                    )
                    """
                )

    # -- predictions ------------------------------------------------------------

    def record_prediction(self, row: Dict[str, Any]) -> Optional[int]:
        """Inserts one permanent prediction row. Returns the new row id, or
        None if this exact (fixture_id, market) was already recorded before
        (duplicate protection -- e.g. the daily archive got recomputed
        twice) -- the existing row is left untouched either way."""
        dedup_key = f"{row.get('fixture_id')}|{row.get('market')}"
        with self._lock, self._conn:
            existing = self._conn.execute(
                "SELECT id FROM predictions WHERE dedup_key = ?", (dedup_key,)
            ).fetchone()
            if existing is not None:
                return None
            cur = self._conn.execute(
                """
                INSERT INTO predictions (
                    created_at, match_datetime, sport, country, league, fixture_id,
                    home_team, away_team, market, market_label, selection, odds,
                    estimated_probability, signal_level, reason, model_version,
                    archive_version, prediction_source, dedup_key
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    self._now_iso(), row.get("match_datetime"), row.get("sport"),
                    row.get("country"), row.get("league"), row.get("fixture_id"),
                    row.get("home_team"), row.get("away_team"), row.get("market"),
                    row.get("market_label"), row.get("selection"), row.get("odds"),
                    row.get("estimated_probability"), row.get("signal_level"),
                    row.get("reason"), row.get("model_version"), row.get("archive_version"),
                    row.get("prediction_source"), dedup_key,
                ),
            )
            return cur.lastrowid

    def get_prediction(self, prediction_id: int) -> Optional[sqlite3.Row]:
        with self._lock:
            return self._conn.execute(
                "SELECT * FROM predictions WHERE id = ?", (prediction_id,)
            ).fetchone()

    def pending_predictions(self, *, before: Optional[str] = None) -> List[sqlite3.Row]:
        """Predictions with no result row yet, optionally restricted to
        those whose match_datetime is already <= `before` (ISO-8601) --
        never touches predictions for matches that have not started yet."""
        query = (
            "SELECT p.* FROM predictions p LEFT JOIN results r ON r.prediction_id = p.id "
            "WHERE r.id IS NULL"
        )
        params: tuple = ()
        if before is not None:
            query += " AND p.match_datetime IS NOT NULL AND p.match_datetime <= ?"
            params = (before,)
        with self._lock:
            return self._conn.execute(query, params).fetchall()

    def all_predictions_with_results(self) -> List[sqlite3.Row]:
        with self._lock:
            return self._conn.execute(
                """
                SELECT p.*, r.final_home_score, r.final_away_score, r.status AS result_status,
                       r.won, r.lost, r.void, r.profit, r.stake, r.checked_at
                FROM predictions p LEFT JOIN results r ON r.prediction_id = p.id
                ORDER BY p.created_at
                """
            ).fetchall()

    # -- results (append-only) ---------------------------------------------------

    def record_result(
        self, *, prediction_id: int, fixture_id: Optional[int], final_home_score: Optional[int],
        final_away_score: Optional[int], status: str, won: bool, lost: bool, void: bool,
        profit: float, stake: float, settlement_explanation: Optional[str] = None,
    ) -> bool:
        """Appends one result row for `prediction_id`. Returns False without
        writing anything if a result already exists for this prediction
        (append-only -- a settled prediction is never re-graded)."""
        with self._lock, self._conn:
            existing = self._conn.execute(
                "SELECT id FROM results WHERE prediction_id = ?", (prediction_id,)
            ).fetchone()
            if existing is not None:
                return False
            self._conn.execute(
                """
                INSERT INTO results (
                    prediction_id, fixture_id, final_home_score, final_away_score, status,
                    won, lost, void, profit, stake, settlement_explanation, checked_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    prediction_id, fixture_id, final_home_score, final_away_score, status,
                    int(won), int(lost), int(void), profit, stake, settlement_explanation,
                    self._now_iso(),
                ),
            )
            return True

    # -- aggregate statistics (materialized, safely rebuildable) ----------------

    def refresh_statistics(self, *, stake: float = DEFAULT_STAKE) -> None:
        """Fully recomputes the five *_statistics tables from the raw,
        append-only predictions/results tables. Safe to call as often as
        needed (e.g. after every result-checker cycle, or on demand before
        rendering a report) -- it never touches predictions/results
        themselves, only rebuilds these derived aggregates."""
        rows = self.all_predictions_with_results()
        buckets: Dict[str, Dict[str, List[sqlite3.Row]]] = {
            "daily_statistics": {}, "monthly_statistics": {},
            "market_statistics": {}, "league_statistics": {}, "signal_statistics": {},
        }
        for row in rows:
            created = row["created_at"] or ""
            day = created[:10] if created else "unknown"
            month = created[:7] if created else "unknown"
            buckets["daily_statistics"].setdefault(day, []).append(row)
            buckets["monthly_statistics"].setdefault(month, []).append(row)
            buckets["market_statistics"].setdefault(row["market"] or "unknown", []).append(row)
            buckets["league_statistics"].setdefault(row["league"] or "unknown", []).append(row)
            buckets["signal_statistics"].setdefault(row["signal_level"] or "unknown", []).append(row)

        now_iso = self._now_iso()
        with self._lock, self._conn:
            for table in buckets:
                self._conn.execute(f"DELETE FROM {table}")
            for table, bucket_map in buckets.items():
                for bucket_key, bucket_rows in bucket_map.items():
                    stats = _aggregate(bucket_rows, stake)
                    self._conn.execute(
                        f"""
                        INSERT INTO {table} (
                            {_bucket_column(table)}, total_predictions, settled_predictions,
                            wins, losses, voids, half_wins, half_losses, win_rate, roi, profit,
                            avg_odds, updated_at
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            bucket_key, stats["total_predictions"], stats["settled_predictions"],
                            stats["wins"], stats["losses"], stats["voids"], stats["half_wins"],
                            stats["half_losses"], stats["win_rate"], stats["roi"], stats["profit"],
                            stats["avg_odds"], now_iso,
                        ),
                    )

    def overall_stats(
        self, *, stake: float = DEFAULT_STAKE, since: Optional[str] = None, until: Optional[str] = None,
    ) -> Dict[str, Any]:
        rows = self.all_predictions_with_results()
        if since is not None:
            rows = [r for r in rows if (r["created_at"] or "") >= since]
        if until is not None:
            rows = [r for r in rows if (r["created_at"] or "") < until]
        return _aggregate(rows, stake)

    def group_stats(
        self, group_col: str, *, stake: float = DEFAULT_STAKE, since: Optional[str] = None, until: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        rows = self.all_predictions_with_results()
        if since is not None:
            rows = [r for r in rows if (r["created_at"] or "") >= since]
        if until is not None:
            rows = [r for r in rows if (r["created_at"] or "") < until]
        grouped: Dict[str, List[sqlite3.Row]] = {}
        for row in rows:
            key = row[group_col] or "unknown"
            grouped.setdefault(key, []).append(row)
        out = []
        for key, group_rows in grouped.items():
            stats = _aggregate(group_rows, stake)
            stats["key"] = key
            out.append(stats)
        return out


def _bucket_column(table: str) -> str:
    return {
        "daily_statistics": "bucket_date",
        "monthly_statistics": "bucket_month",
        "market_statistics": "market",
        "league_statistics": "league",
        "signal_statistics": "signal_level",
    }[table]


def _aggregate(rows: List[sqlite3.Row], stake: float) -> Dict[str, Any]:
    total = len(rows)
    settled = wins = losses = voids = half_wins = half_losses = 0
    profit = 0.0
    odds_values: List[float] = []
    for row in rows:
        status = row["result_status"]
        if status is None:
            continue
        if row["odds"] is not None:
            odds_values.append(row["odds"])
        if status in WIN_STATUSES:
            wins += 1
            settled += 1
            if status == "half_won":
                half_wins += 1
        elif status in LOSS_STATUSES:
            losses += 1
            settled += 1
            if status == "half_lost":
                half_losses += 1
        elif status in VOID_RESULT_STATUSES:
            voids += 1
            settled += 1
        # "unresolved" is intentionally excluded from settled_predictions.
        row_profit = row["profit"]
        if row_profit is not None:
            profit += row_profit

    decisive = wins + losses
    win_rate = round((wins / decisive) * 100.0, 2) if decisive else 0.0
    staked_settled = wins + losses + voids
    roi = round((profit / (stake * staked_settled)) * 100.0, 2) if staked_settled else 0.0
    avg_odds = round(sum(odds_values) / len(odds_values), 3) if odds_values else 0.0

    return {
        "total_predictions": total,
        "settled_predictions": settled,
        "wins": wins,
        "losses": losses,
        "voids": voids,
        "half_wins": half_wins,
        "half_losses": half_losses,
        "win_rate": win_rate,
        "roi": roi,
        "profit": round(profit, 2),
        "avg_odds": avg_odds,
    }
